spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neuronurture
    username: postgres
    password: pscjscsschsc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://abhishekcse4:pscjscsschsc@cluster0.dqxwxgp.mongodb.net/neuronurture_tickets?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8082

sendgrid:
  api-key: 
  from-email: tarekahmad484@gmail.com
  from-name: NeuroNurture





