spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: doctor-service

server:
  port: 8093

jwt:
  secret: c14be041f7be953106853d0d25ff6b7c769afc3278ffce7923a8145f93231dfa
  expiration: 86400000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/







